### ISSUE TITLE
Apparmor gotcha

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity-admindocs#10]
If there's a apparmor profile set on the host, it will affect a binary ran in the container.

For example, the file:  `/etc/apparmor.d/usr.sbin.mysqld`  -- was set on a Ubuntu 18 host. When trying to run `/usr/sbin/mysqld` in a container, it would error with:

```
/usr/sbin/mysqld: Can't read dir of '/etc/mysql/mariadb.conf.d/' (Errcode: 13 "Permission denied")
/usr/sbin/mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 "Permission denied")
```

The host apparmor profile had:
```
# Allow config access
  /etc/mysql/** r,
```

Which was blocking what was being attempted.

**Comment by DrDaveD** [comment]
This seems to me to be intuitive.  I don't think it needs to be documented specially.
