### ISSUE TITLE
View latest docs without generating locally

### ISSUE THREAD

**Issue by coatless** [apptainer/singularity-admindocs#87]
Presently, documentation for singularity is fixed at released version numbers, e.g. 3.4/3.5; however, this does not account for mid-release changes to the documentation. Would it be possible to have a latest/developer version automatically rendered or included?

I only bring this up because I encountered a program while trying to do a non-root user installation and the steps given in the documentation ( https://sylabs.io/guides/3.5/admin-guide/installation.html#unprivileged-non-setuid-installation ) were inaccurate but was later fixed in https://github.com/hpcng/singularity-admindocs/commit/262b2a9d80781e629f630c48b2d02e45a44100ce#diff-4a71eb4df39e92bfe5f68b431be00b8c.

**Comment by DrDaveD** [comment]
The documentation for the master branch is already automatically generated.
